package com.enviro.assessment.grad001.christiantshukudu.investment.Model;

import lombok.*;

import javax.persistence.*;

@Entity
@Table(name = "Invests")
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@ToString

public class Investor {
    // @Id indicates that this field represents the primary key of the entity.
    // @GeneratedValue(strategy = GenerationType.IDENTITY) specifies that the
    // primary key value will be automatically generated by the database,
    // typically using an auto-incrementing column in the table.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // These fields represent properties of the Investor entity.
    private Long id;
    private String name;
    private String address;
    private String contact;

    // getters and setters methods
}
