package com.enviro.assessment.grad001.christiantshukudu.investment.Model;

import java.math.BigDecimal;

import javax.persistence.*;

import lombok.*;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@ToString

public class Product {
  // @Id indicates that this field represents the primary key of the entity.
  // @GeneratedValue(strategy = GenerationType.IDENTITY) specifies that the
  // primary key value will be automatically generated by the database,
  // typically using an auto-incrementing column in the table.
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  // These fields represent properties of the Product entity.
  private Long id;
  private String type;
  private String name;
  private BigDecimal currentBalance;
  // getters and setters methods
}
